"""Compile the normalized content catalog into the sibling APWorld.

The generated module is intentionally boring Python so Archipelago never needs
to import the mod repository at runtime.  ``--check`` is suitable for CI.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from content_catalog import ContentCatalog, load_content_catalog


MOD_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = MOD_ROOT.parent / "Archipelago" / "worlds" / "doometernal" / "generated_content.py"


def _runtime_region(catalog: ContentCatalog, name: str) -> str:
    if "Weapon Mastery Challenge" in name:
        return "Weapon Masteries"
    for spec in catalog.maps.values():
        if name.startswith(f"{spec.display_name} -"):
            return spec.display_name
    raise ValueError(f"runtime location has no map/region owner: {name}")


def render(catalog: ContentCatalog, selected_map: str | None = None) -> str:
    physical = [item for item in catalog.physical_locations if selected_map in (None, item.map_key)]
    if selected_map is not None and selected_map not in catalog.maps:
        raise ValueError(f"unknown map key: {selected_map}")
    # A full APWorld table must remain complete. --map is a validation/filter
    # selector for catalog discovery, not a partial generated module.
    if selected_map is not None:
        physical = list(catalog.physical_locations)
    rows = [(item.name, item.location_id, item.region) for item in physical]
    rows.extend((item.name, item.location_id, _runtime_region(catalog, item.name)) for item in catalog.runtime_locations)
    route = catalog.route
    rows.extend((item["name"], None, item["region"]) for item in route.get("virtual_locations", []))
    if len({name for name, _, _ in rows}) != len(rows):
        raise ValueError("generated APWorld locations are not unique")
    by_region: dict[str, list[str]] = {}
    for name, _, region in rows:
        by_region.setdefault(region, []).append(name)
    lines = [
        '"""GENERATED by tools.content.compile_content_catalog; do not edit."""',
        "",
        "# This file has no timestamp: stable input yields a stable diff.",
    ]
    identity = json.loads(
        (catalog.root / "data" / "content_identity.json").read_text(encoding="utf-8")
    )
    goal_publisher = next(
        publisher for publisher in catalog.publishers
        if any(effect["strategy"] == "campaign_goal" for effect in publisher.effects)
    )
    goal_location = next(
        item.name for item in catalog.runtime_locations
        if item.mission_key == goal_publisher.map_key
        and item.category == "mission_complete"
    )
    lines.extend([
        f"CONTENT_SCHEMA_VERSION = {identity['content_schema_version']!r}",
        f"CONTENT_REVISION = {identity['content_revision']!r}",
        f"BRIDGE_PROTOCOL_VERSION = {identity['bridge_protocol_version']!r}",
        "",
        "LOCATION_ROWS = (",
    ])
    lines.extend(f"    ({name!r}, {code!r}, {region!r})," for name, code, region in rows)
    lines.extend([
        ")",
        "LOCATION_NAME_TO_ID = {name: code for name, code, _ in LOCATION_ROWS if code is not None}",
        "LOCATION_NAMES_BY_REGION = {",
    ])
    for region in sorted(by_region):
        lines.append(f"    {region!r}: {tuple(by_region[region])!r},")
    lines.extend([
        "}",
        f"CAMPAIGN_REGIONS = {tuple(route['regions'])!r}",
        f"CAMPAIGN_CONNECTIONS = {tuple(tuple(row) for row in route['connections'])!r}",
        f"CAMPAIGN_GOAL_LOCATION = {goal_location!r}",
        "RUNTIME_LOCATION_NAMES = frozenset({",
    ])
    lines.extend(f"    {item.name!r}," for item in catalog.runtime_locations)
    lines.extend(["})", ""])
    return "\n".join(lines)


def compile_catalog(
    output: Path = DEFAULT_OUTPUT,
    *,
    output_root: Path | None = None,
    check: bool = False,
    map_key: str | None = None,
) -> bool:
    catalog = load_content_catalog()
    rendered = render(catalog, map_key)
    changed = False

    def write_artifact(path: Path, payload: str) -> None:
        nonlocal changed
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if check:
            if current != payload:
                raise ValueError(f"component=compiled_content file={path} field=synchronization value=stale")
        elif current != payload:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(payload, encoding="utf-8", newline="\n")
            changed = True

    current = output.read_text(encoding="utf-8") if output.exists() else ""
    if check:
        if current != rendered:
            raise ValueError(
                f"component=apworld file={output} field=generated_content value=stale\n"
                "Reproduce:\n"
                "  python -m tools.content.compile_content_catalog --check\n"
                "Fix:\n"
                "  python -m tools.content.compile_content_catalog"
            )
    else:
        if current != rendered:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(rendered, encoding="utf-8", newline="\n")
            changed = True

    if output_root is None:
        output_root = MOD_ROOT / "build" / "staging" / "runtime_catalog"

    output_root.mkdir(parents=True, exist_ok=True)

    staging_gen = output_root / "generated_content.py"
    current_gen = staging_gen.read_text(encoding="utf-8") if staging_gen.exists() else ""
    if current_gen != rendered:
        if not check:
            staging_gen.write_text(rendered, encoding="utf-8", newline="\n")
            changed = True

    for json_name in ["content_identity.json", "items.json", "item_replay_policies.json"]:
        src = catalog.root / "data" / json_name
        if src.exists():
            content_bytes = src.read_bytes()
            dst = output_root / json_name
            current_bytes = dst.read_bytes() if dst.exists() else b""
            if current_bytes != content_bytes:
                if not check:
                    dst.write_bytes(content_bytes)
                    changed = True

    from challenge_registry import challenge_registry_document
    from map_registry import _catalog_registry
    from publisher_contracts import publisher_contracts_document
    compiled_sources = _catalog_registry(catalog.root)
    sources_rendered = json.dumps(compiled_sources, indent=2, sort_keys=True) + "\n"
    generated_data = {
        "map_sources.json": compiled_sources,
        "location_names.json": {
            "schema_version": 1,
            "source": "content/maps/*/locations.json + runtime.json",
            "locations": {str(item.location_id): item.name for item in (*catalog.physical_locations, *catalog.runtime_locations)},
        },
        "runtime_locations.json": {item.name: item.location_id for item in catalog.runtime_locations},
        "challenge_location_registry.json": challenge_registry_document(catalog),
        "publisher_contracts.json": publisher_contracts_document(catalog.publishers),
        "campaign_goal_contract.json": dict(catalog.campaign_goal),
    }
    for name, value in generated_data.items():
        rendered_json = json.dumps(value, indent=2, sort_keys=True) + "\n"
        write_artifact(catalog.root / "data" / name, rendered_json)
        write_artifact(output_root / name, rendered_json)
    for spec in catalog.maps.values():
        locations = json.loads(spec.level_config_path.read_text(encoding="utf-8"))
        manifest = dict(locations.get("entities", {}))
        manifest.update({
            item.get("ap_check", f"AP_CHECK_SECRET_{item['location_id']}"): item["location_id"]
            for item in locations.get("secret_encounters", [])
        })
        write_artifact(catalog.root / "manifests" / f"{spec.key}.json",
                       json.dumps(manifest, indent=4) + "\n")

    from foundation import load_foundation_contracts
    compiled_foundation = load_foundation_contracts(authorial=True)
    foundation_rendered = json.dumps(compiled_foundation, indent=2, sort_keys=True) + "\n"
    for dst_path in [output_root / "foundation_contracts.json", catalog.root / "data" / "foundation_contracts.json"]:
        curr = dst_path.read_text(encoding="utf-8") if dst_path.exists() else ""
        if curr != foundation_rendered:
            if not check:
                dst_path.parent.mkdir(parents=True, exist_ok=True)
                dst_path.write_text(foundation_rendered, encoding="utf-8", newline="\n")
                changed = True

    identity_src = catalog.root / "data" / "content_identity.json"
    identity_data = json.loads(identity_src.read_text(encoding="utf-8")) if identity_src.exists() else {}

    catalog_dict = {
        "maps": list(catalog.maps.keys()),
        "physical_locations_count": len(catalog.physical_locations),
        "revision": identity_data.get("content_revision", "v0.3.5-alpha.2"),
        "runtime_locations_count": len(catalog.runtime_locations),
        "schema_version": identity_data.get("content_schema_version", 2),
    }
    catalog_rendered = json.dumps(catalog_dict, indent=2, sort_keys=True) + "\n"
    staging_catalog = output_root / "catalog.json"
    current_catalog = staging_catalog.read_text(encoding="utf-8") if staging_catalog.exists() else ""
    if current_catalog != catalog_rendered:
        if not check:
            staging_catalog.write_text(catalog_rendered, encoding="utf-8", newline="\n")
            changed = True

    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--map", dest="map_key")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--output-root", type=Path, default=None)
    args = parser.parse_args()
    changed = compile_catalog(
        args.output,
        output_root=args.output_root,
        check=args.check,
        map_key=args.map_key,
    )
    print("updated" if changed else "up-to-date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
