"""Compile the normalized content catalog into the sibling APWorld.

The generated module is intentionally boring Python so Archipelago never needs
to import the mod repository at runtime.  ``--check`` is suitable for CI.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from content_catalog import ContentCatalog, load_content_catalog


MOD_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = MOD_ROOT.parent / "Archipelago" / "worlds" / "doometernal" / "generated_content.py"


def _runtime_region(catalog: ContentCatalog, name: str) -> str:
    if "Weapon Mastery Challenge" in name:
        return "Weapon Masteries"
    for spec in catalog.maps.values():
        if name.startswith(f"{spec.display_name} -"):
            return spec.display_name
    raise ValueError(f"runtime location has no map/region owner: {name}")


def render(catalog: ContentCatalog, selected_map: str | None = None) -> str:
    physical = [item for item in catalog.physical_locations if selected_map in (None, item.map_key)]
    if selected_map is not None and selected_map not in catalog.maps:
        raise ValueError(f"unknown map key: {selected_map}")
    # A full APWorld table must remain complete. --map is a validation/filter
    # selector for catalog discovery, not a partial generated module.
    if selected_map is not None:
        physical = list(catalog.physical_locations)
    rows = [(item.name, item.location_id, item.region) for item in physical]
    rows.extend((item.name, item.location_id, _runtime_region(catalog, item.name)) for item in catalog.runtime_locations)
    route = __import__("json").loads((catalog.root / "data" / "campaign_route.json").read_text(encoding="utf-8"))
    rows.extend((item["name"], None, item["region"]) for item in route.get("virtual_locations", []))
    if len({name for name, _, _ in rows}) != len(rows):
        raise ValueError("generated APWorld locations are not unique")
    by_region: dict[str, list[str]] = {}
    for name, _, region in rows:
        by_region.setdefault(region, []).append(name)
    lines = [
        '"""GENERATED by tools.content.compile_content_catalog; do not edit."""',
        "",
        "# This file has no timestamp: stable input yields a stable diff.",
        "LOCATION_ROWS = (",
    ]
    lines.extend(f"    ({name!r}, {code!r}, {region!r})," for name, code, region in rows)
    lines.extend([
        ")",
        "LOCATION_NAME_TO_ID = {name: code for name, code, _ in LOCATION_ROWS if code is not None}",
        "LOCATION_NAMES_BY_REGION = {",
    ])
    for region in sorted(by_region):
        lines.append(f"    {region!r}: {tuple(by_region[region])!r},")
    lines.extend([
        "}",
        f"CAMPAIGN_REGIONS = {tuple(route['regions'])!r}",
        f"CAMPAIGN_CONNECTIONS = {tuple(tuple(row) for row in route['connections'])!r}",
        "RUNTIME_LOCATION_NAMES = frozenset({",
    ])
    lines.extend(f"    {item.name!r}," for item in catalog.runtime_locations)
    lines.extend(["})", ""])
    return "\n".join(lines)


def compile_catalog(output: Path = DEFAULT_OUTPUT, *, check: bool = False, map_key: str | None = None) -> bool:
    rendered = render(load_content_catalog(), map_key)
    current = output.read_text(encoding="utf-8") if output.exists() else ""
    if check:
        if current != rendered:
            raise ValueError(f"generated content is stale: {output}")
        return False
    if current != rendered:
        output.write_text(rendered, encoding="utf-8", newline="\n")
        return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--map", dest="map_key")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    changed = compile_catalog(args.output, check=args.check, map_key=args.map_key)
    print("updated" if changed else "up-to-date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
