"""Compile the normalized content catalog into a standalone APWorld module."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from doom_eap.content.content_catalog import ContentCatalog, load_content_catalog

MOD_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = MOD_ROOT.parent / "Archipelago" / "worlds" / "doometernal" / "generated_content.py"


def render(catalog: ContentCatalog, selected_map: str | None = None) -> str:
    physical = [item for item in catalog.physical_locations if selected_map in (None, item.map_key)]
    if selected_map is not None and selected_map not in catalog.maps:
        raise ValueError(f"unknown map key: {selected_map}")
    # --map narrows catalog discovery while output remains a complete APWorld table.
    if selected_map is not None:
        physical = list(catalog.physical_locations)
    rows: list[tuple[str, int | None, str]] = [
        (item.name, item.location_id, item.region) for item in physical
    ]
    rows.extend(
        (item.name, item.location_id, item.region) for item in catalog.runtime_locations
    )
    route = catalog.route
    rows.extend((item["name"], None, item["region"]) for item in route.get("virtual_locations", []))
    if len({name for name, _, _ in rows}) != len(rows):
        raise ValueError("generated APWorld locations are not unique")
    by_region: dict[str, list[str]] = {}
    for name, _, region in rows:
        by_region.setdefault(region, []).append(name)

    def string(value: str) -> str:
        return json.dumps(value, ensure_ascii=False)

    lines = [
        '"""GENERATED by tools.content.compile_content_catalog; do not edit."""',
        "",
        "# This file has no timestamp: stable input yields a stable diff.",
    ]
    identity = json.loads((catalog.root / "data" / "content_identity.json").read_text(encoding="utf-8"))
    goal_publisher = next(
        publisher
        for publisher in catalog.publishers
        if any(effect["strategy"] == "campaign_goal" for effect in publisher.effects)
    )
    goal_location = next(
        item.name
        for item in catalog.runtime_locations
        if item.mission_key == goal_publisher.map_key and item.category == "mission_complete"
    )
    lines.extend(
        [
            f"CONTENT_SCHEMA_VERSION = {identity['content_schema_version']!r}",
            f"CONTENT_REVISION = {string(identity['content_revision'])}",
            f"BRIDGE_PROTOCOL_VERSION = {identity['bridge_protocol_version']!r}",
            f"COMPILER_REVISION = {identity['compiler_revision']!r}",
            f"SESSION_MOD_CONTRACT_REVISION = {identity['session_mod_contract_revision']!r}",
            "",
            "LOCATION_ROWS = (",
        ]
    )
    for name, code, region in rows:
        line = f"    ({string(name)}, {code!r}, {string(region)}),"
        if len(line) <= 120:
            lines.append(line)
        else:
            lines.extend(
                [
                    "    (",
                    f"        {string(name)},",
                    f"        {code!r},",
                    f"        {string(region)},",
                    "    ),",
                ]
            )
    lines.extend(
        [
            ")",
            "LOCATION_NAME_TO_ID = {name: code for name, code, _ in LOCATION_ROWS if code is not None}",
            "LOCATION_NAMES_BY_REGION = {",
        ]
    )
    for region in sorted(by_region):
        lines.append(f"    {string(region)}: (")
        lines.extend(f"        {string(name)}," for name in by_region[region])
        lines.append("    ),")
    lines.extend(
        [
            "}",
            "CAMPAIGN_REGIONS = (",
        ]
    )
    lines.extend(f"    {string(region)}," for region in route["regions"])
    lines.extend(
        [
            ")",
            "CAMPAIGN_CONNECTIONS = (",
        ]
    )
    for source, destination, entrance, condition in route["connections"]:
        lines.append(
            f"    ({string(source)}, {string(destination)}, {string(entrance)}, {dict(condition)!r}),"
        )
    lines.extend(
        [
            ")",
            f"CAMPAIGN_GOAL_LOCATION = {string(goal_location)}",
            "RUNTIME_LOCATION_NAMES = frozenset({",
        ]
    )
    lines.extend(f"    {string(item.name)}," for item in catalog.runtime_locations)
    lines.extend(["})", ""])
    return "\n".join(lines)


def _compile_catalog(
    output: Path = DEFAULT_OUTPUT,
    *,
    output_root: Path | None = None,
    check: bool = False,
    map_key: str | None = None,
    source_only: bool = False,
) -> tuple[Path, ...]:
    catalog = load_content_catalog()
    rendered = render(catalog, map_key)
    changed_paths: list[Path] = []

    def write_artifact(path: Path, payload: str) -> None:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if check:
            if current != payload:
                raise ValueError(f"component=compiled_content file={path} field=synchronization value=stale")
        elif current != payload:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(payload, encoding="utf-8", newline="\n")
            changed_paths.append(path)

    def write_bytes_artifact(path: Path, payload: bytes) -> None:
        current = path.read_bytes() if path.is_file() else None
        if check:
            if current != payload:
                raise ValueError(
                    f"component=compiled_content file={path} field=synchronization value=stale"
                )
        elif current != payload:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(payload)
            changed_paths.append(path)

    write_artifact(output, rendered)

    if source_only:
        return tuple(changed_paths)

    if output_root is None:
        output_root = MOD_ROOT / "build" / "staging" / "runtime_catalog"

    staging_gen = output_root / "generated_content.py"
    write_artifact(staging_gen, rendered)

    for json_name in ["content_identity.json", "items.json", "item_replay_policies.json"]:
        src = catalog.root / "data" / json_name
        if src.exists():
            content_bytes = src.read_bytes()
            dst = output_root / json_name
            write_bytes_artifact(dst, content_bytes)

    from doom_eap.contracts.challenge_registry import challenge_registry_document
    from doom_eap.content.map_registry import _catalog_registry
    from doom_eap.contracts.publisher_contracts import publisher_contracts_document
    from doom_eap.content.automap_visual_registry import build_authorial_registry

    compiled_sources = _catalog_registry(catalog.root)

    generated_data = {
        "map_sources.json": compiled_sources,
        "location_names.json": {
            "schema_version": 1,
            "source": "content/maps/*/locations.json + runtime.json",
            "locations": {
                str(item.location_id): item.name for item in (*catalog.physical_locations, *catalog.runtime_locations)
            },
        },
        "runtime_locations.json": {item.name: item.location_id for item in catalog.runtime_locations},
        "challenge_location_registry.json": challenge_registry_document(catalog),
        "publisher_contracts.json": publisher_contracts_document(catalog.publishers),
        "campaign_goal_contract.json": dict(catalog.campaign_goal),
        "checked_location_visuals.json": build_authorial_registry(catalog.root),
    }
    for name, value in generated_data.items():
        rendered_json = json.dumps(value, indent=2, sort_keys=True) + "\n"
        write_artifact(catalog.root / "data" / name, rendered_json)
        write_artifact(output_root / name, rendered_json)
    for spec in catalog.maps.values():
        locations = json.loads(spec.level_config_path.read_text(encoding="utf-8"))
        manifest = dict(locations.get("entities", {}))
        manifest.update(
            {
                item.get("ap_check", f"AP_CHECK_SECRET_{item['location_id']}"): item["location_id"]
                for item in locations.get("secret_encounters", [])
            }
        )
        write_artifact(
            catalog.root / "manifests" / f"{spec.key}.json",
            json.dumps(manifest, indent=4) + "\n",
        )

    from doom_eap.contracts.foundation import load_foundation_contracts

    compiled_foundation = load_foundation_contracts(authorial=True)
    foundation_rendered = json.dumps(compiled_foundation, indent=2, sort_keys=True) + "\n"
    for dst_path in [output_root / "foundation_contracts.json", catalog.root / "data" / "foundation_contracts.json"]:
        write_artifact(dst_path, foundation_rendered)

    identity_src = catalog.root / "data" / "content_identity.json"
    identity_data = json.loads(identity_src.read_text(encoding="utf-8")) if identity_src.exists() else {}

    catalog_dict = {
        "maps": list(catalog.maps.keys()),
        "physical_locations_count": len(catalog.physical_locations),
        "revision": identity_data.get("content_revision", "v0.3.5-alpha.2"),
        "runtime_locations_count": len(catalog.runtime_locations),
        "schema_version": identity_data.get("content_schema_version", 2),
    }
    catalog_rendered = json.dumps(catalog_dict, indent=2, sort_keys=True) + "\n"
    staging_catalog = output_root / "catalog.json"
    write_artifact(staging_catalog, catalog_rendered)

    return tuple(changed_paths)


def materialize_catalog(
    output: Path = DEFAULT_OUTPUT,
    *,
    output_root: Path | None = None,
    map_key: str | None = None,
    source_only: bool = False,
) -> tuple[Path, ...]:
    return _compile_catalog(
        output,
        output_root=output_root,
        map_key=map_key,
        source_only=source_only,
    )


def check_catalog(
    output: Path = DEFAULT_OUTPUT,
    *,
    output_root: Path | None = None,
    map_key: str | None = None,
    source_only: bool = False,
) -> None:
    _compile_catalog(
        output,
        output_root=output_root,
        check=True,
        map_key=map_key,
        source_only=source_only,
    )


def compile_catalog(
    output: Path = DEFAULT_OUTPUT,
    *,
    output_root: Path | None = None,
    check: bool = False,
    map_key: str | None = None,
    source_only: bool = False,
) -> bool:
    return bool(
        _compile_catalog(
            output,
            output_root=output_root,
            check=check,
            map_key=map_key,
            source_only=source_only,
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--map", dest="map_key")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--output-root", type=Path, default=None)
    parser.add_argument("--source-only", action="store_true")
    args = parser.parse_args()
    changed = compile_catalog(
        args.output,
        output_root=args.output_root,
        check=args.check,
        map_key=args.map_key,
        source_only=args.source_only,
    )
    print("updated" if changed else "up-to-date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
