name: "💡 Feature Request"
description: Suggest something you would like DoomEAP to do.
body:
  - type: textarea
    id: request
    attributes:
      label: What would you like DoomEAP to do?
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Why would this be useful?
