[
    uuid(1c9ca7c8-d421-482d-b85d-79fac33b2658),
    version(1.0),
    implicit_handle(handle_t ap_runtime_rpc__MIDL_AutoBindHandle)
]
interface ap_runtime_rpc
{
    void ap_execute(
        [in, string] unsigned char* command);
    void ap_request_entities(
        [in, string] unsigned char* path,
        [in] boolean begin,
        [in] int size);
    void ap_upload_chunk(
        [in] int size,
        [in] int offset,
        [in, size_is(size)] unsigned char* data);
    void ap_retrieve_entities(
        [in, out] int* size,
        [out, size_is(*size)] unsigned char* data);
    void ap_retrieve_encounter(
        [in, out] int* size,
        [out, size_is(*size)] unsigned char* data);
    void ap_retrieve_checkpoint(
        [in, out] int* size,
        [out, size_is(*size)] unsigned char* data);
    void ap_retrieve_spawn(
        [in, out] int* size,
        [out, size_is(*size)] unsigned char* data);
    void ap_health(
        [in, out] int* state);
}
